"""Add settings table

Revision ID: cf29d02b1417
Revises: f3ac4b7fd745
Create Date: 2025-06-05 18:09:25.279171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf29d02b1417'
down_revision = 'f3ac4b7fd745'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    
    # Insert default settings
    settings_table = sa.table('settings',
        sa.column('key', sa.String),
        sa.column('value', sa.JSON),
        sa.column('description', sa.String),
        sa.column('is_system', sa.Boolean)
    )
    
    op.bulk_insert(settings_table, [
        {
            'key': 'ip_detection.ipv4_sources',
            'value': ["https://api.ipify.org", "https://ifconfig.me/ip", "https://icanhazip.com", "https://ident.me", "https://checkip.amazonaws.com"],
            'description': 'List of IPv4 detection services',
            'is_system': True
        },
        {
            'key': 'ip_detection.ipv6_sources',
            'value': ["https://api6.ipify.org", "https://ifconfig.me/ip", "https://icanhazip.com", "https://ident.me"],
            'description': 'List of IPv6 detection services',
            'is_system': True
        },
        {
            'key': 'scheduler.refresh_interval',
            'value': 300,
            'description': 'DNS check interval in seconds',
            'is_system': True
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###