"""Add Slack integration

Revision ID: f3ac4b7fd745
Revises: 34d97e9d0bce
Create Date: 2025-06-05 17:35:26.166053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ac4b7fd745'
down_revision = '34d97e9d0bce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_accounts_id'), 'slack_accounts', ['id'], unique=False)
    op.add_column('domains', sa.Column('slack_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'domains', 'slack_accounts', ['slack_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.drop_column('domains', 'slack_account_id')
    op.drop_index(op.f('ix_slack_accounts_id'), table_name='slack_accounts')
    op.drop_table('slack_accounts')
    # ### end Alembic commands ###